# Generated by Django 3.1.3 on 2020-12-26 16:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('cardImage', models.CharField(max_length=200)),
                ('model_taget', models.CharField(max_length=200, unique=True)),
                ('model_imgage', models.CharField(max_length=200)),
                ('models_description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
