# Generated by Django 3.1.3 on 2020-12-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='short',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
