# Generated by Django 3.1.3 on 2020-12-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201227_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='img',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
